"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Experiment = { id: number; date: string; purpose: string; method: string; result: string; status: "已完成" | "待复核" };
const seed: Experiment[] = [
  { id: 1, date: "2026-08-18", purpose: "浓度筛选", method: "Cell viability assay", result: "确定 10 μM 为后续测试浓度", status: "已完成" },
  { id: 2, date: "2026-08-20", purpose: "验证 Treatment X 对迁移能力的影响", method: "Transwell migration assay", result: "第 2 次重复背景偏高，待复核", status: "待复核" },
];
const tabs = [["today", "今日实验"], ["timeline", "项目时间线"], ["literature", "文献证据"], ["weekly", "本周成文"]];

export default function Home() {
  const [tab, setTab] = useState("today"); const [items, setItems] = useState<Experiment[]>(seed); const [saved, setSaved] = useState(false); const [reviewed, setReviewed] = useState(false);
  useEffect(() => { const data = localStorage.getItem("labflow-experiments"); if (data) setItems(JSON.parse(data)); }, []);
  useEffect(() => localStorage.setItem("labflow-experiments", JSON.stringify(items)), [items]);
  const status = useMemo(() => ({ done: items.filter(x => x.status === "已完成").length, review: items.filter(x => x.status === "待复核").length }), [items]);
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); setItems(v => [{ id: Date.now(), date: String(f.get("date")), purpose: String(f.get("purpose")), method: String(f.get("method")), result: String(f.get("result")), status: "待复核" }, ...v]); setSaved(true); e.currentTarget.reset(); }
  return <main className="min-h-screen bg-slate-50 text-slate-900"><header><div className="shell py-7"><p className="brand">LABFLOW · PERSONAL RESEARCH SYSTEM</p><div className="heading"><div><h1>让实验记录自然长成论文</h1><p>课题：Treatment X 调控细胞迁移</p></div><span className="summary">本周：{status.done} 项完成 · {status.review} 项待复核</span></div></div></header><nav className="shell tabs" aria-label="主导航">{tabs.map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={tab === id ? "active" : ""}>{label}</button>)}</nav><section className="shell pb-12">
    {tab === "today" && <div className="grid"><form className="panel" onSubmit={submit}><h2>记录一次实验</h2><p className="hint">记录真实、可复核的信息；论文写作会在证据确认后发生。</p><div className="two"><Field label="实验日期"><input name="date" type="date" defaultValue="2026-08-20" required /></Field><Field label="实验方法"><input name="method" defaultValue="Transwell migration assay" required /></Field></div><Field label="本次目的"><input name="purpose" placeholder="例如：验证 Treatment X 对迁移能力的影响" required /></Field><Field label="结果与异常"><textarea name="result" placeholder="写下观察结果、异常、待复核项和下一步。" required /></Field><button className="primary">保存实验记录</button>{saved && <p className="success">已保存并标记为“待复核”，不会自动成为论文结论。</p>}</form><aside className="panel"><h2>保存后会做什么</h2><Item title="实验卡片" text="目的、方法、结果与下一步进入项目时间线。"/><Item title="证据待办" text="补齐原始图、统计表、图号与实验批次。"/><Item title="每周成文" text="只把“证据完整”的内容送进英文草稿。"/></aside></div>}
    {tab === "timeline" && <div className="grid"><section className="panel"><h2>项目时间线</h2><div className="timeline">{items.map(x => <article className="record" key={x.id}><time>{x.date}</time><div><h3>{x.purpose} <span className={x.status === "已完成" ? "done tag" : "tag"}>{x.status}</span></h3><p>{x.method}</p><p className="muted">{x.result}</p></div></article>)}</div></section><aside className="panel"><h2>核心研究问题</h2><blockquote>Treatment X 是否在当前实验条件下与迁移增强有关？</blockquote><p className="hint">当前结论边界：尚不能推断转移机制；仍需重复数据、统计分析和机制实验。</p></aside></div>}
    {tab === "literature" && <div className="grid"><section className="panel"><h2>已关联文献</h2><Item title="Author et al., 2024 · Discussion" text="提示该通路可能参与细胞运动调控；需核对原文具体结论。"/><Item title="Author et al., 2022 · Methods" text="提供 Transwell assay 的方法学比较。"/></section><aside className="panel"><h2>引用纪律</h2><p className="hint">只有已阅读、已核对的原始论文，才能支持具体论点。导入 PDF 不等于完成引用。</p><button onClick={() => alert("下一步可接入 Zotero 导入与 DOI 检索。")} className="secondary">规划 Zotero 导入</button></aside></div>}
    {tab === "weekly" && <div className="grid"><section className="panel"><p className="brand">RESULTS · DRAFT CANDIDATE</p><h2>本周可写入 Results 的内容</h2><blockquote>在测试条件下，Treatment X 组显示更高的迁移细胞数；在复核独立重复、统计方法和图号前，该结果不应被视为机制性结论。</blockquote><h3>英文草稿（待人工确认）</h3><p className="draft">Under the tested conditions, Treatment X was associated with an increase in cell migration relative to the control group. This observation will be interpreted after verification of the replicate-level data and statistical analysis.</p><button className="primary" onClick={() => setReviewed(true)}>{reviewed ? "已标记为人工确认" : "标记为“已人工确认”"}</button></section><aside className="panel"><h2>本周证据清单</h2><ul><li>✓ 实验目的与条件</li><li>△ 原始图像与统计表</li><li>△ 图号和统计方法</li><li>✓ 文献背景笔记</li></ul><p className="hint">系统会保留“证据不足”的标记，避免夸大实验结论。</p></aside></div>}
  </section></main>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
function Item({ title, text }: { title: string; text: string }) { return <div className="item"><strong>{title}</strong><span>{text}</span></div>; }
